// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Assignment_03_EF.Models
{
    public partial class CustOrderHistResult
    {
        public string ProductName { get; set; }
        public int? Total { get; set; }
    }
}
